In [40]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import os
#from arch import arch_model
from statsmodels.graphics.tsaplots import plot_acf,plot_pacf
import seaborn as sns

df = pd.read_csv("loans_full_schema.csv")
df

,emp_title,emp_length,state,homeownership,annual_income,verified_income,debt_to_income,annual_income_joint,verification_income_joint,debt_to_income_joint,...,sub_grade,issue_month,loan_status,initial_listing_status,disbursement_method,balance,paid_total,paid_principal,paid_interest,paid_late_fees
0,global config engineer,3.0,NJ,MORTGAGE,90000.0,Verified,18.01,NaN,NaN,NaN,...,C3,Mar-2018,Current,whole,Cash,27015.86,1999.33,984.14,1015.19,0.0
1,warehouse office clerk,10.0,HI,RENT,40000.0,Not Verified,5.04,NaN,NaN,NaN,...,C1,Feb-2018,Current,whole,Cash,4651.37,499.12,348.63,150.49,0.0
2,assembly,3.0,WI,RENT,40000.0,Source Verified,21.15,NaN,NaN,NaN,...,D1,Feb-2018,Current,fractional,Cash,1824.63,281.80,175.37,106.43,0.0
3,customer service,1.0,PA,RENT,30000.0,Not Verified,10.16,NaN,NaN,NaN,...,A3,Jan-2018,Current,whole,Cash,18853.26,3312.89,2746.74,566.15,0.0
4,security supervisor,10.0,CA,RENT,35000.0,Verified,57.96,57000.0,Verified,37.66,...,C3,Mar-2018,Current,whole,Cash,21430.15,2324.65,1569.85,754.80,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,owner,10.0,TX,RENT,108000.0,Source Verified,22.28,NaN,NaN,NaN,...,A4,Jan-2018,Current,whole,Cash,21586.34,2969.80,2413.66,556.14,0.0
9996,director,8.0,PA,MORTGAGE,121000.0,Verified,32.38,NaN,NaN,NaN,...,D3,Feb-2018,Current,whole,Cash,9147.44,1456.31,852.56,603.75,0.0
9997,toolmaker,10.0,CT,MORTGAGE,67000.0,Verified,45.26,107000.0,Source Verified,29.57,...,E2,Feb-2018,Current,fractional,Cash,27617.65,4620.80,2382.35,2238.45,0.0
9998,manager,1.0,WI,MORTGAGE,80000.0,Source Verified,11.99,NaN,NaN,NaN,...,A1,Feb-2018,Current,whole,Cash,21518.12,2873.31,2481.88,391.43,0.0
9999,operations analyst,3.0,CT,RENT,66000.0,Not Verified,20.82,NaN,NaN,NaN,...,B4,Feb-2018,Current,whole,Cash,11574.83,1658.56,1225.17,433.39,0.0

Q - Hypothesis on which factors influence if someone will pay their loan back?

1.factors: debt to income ratio (higher or lower);

2.loan status (current or not current)

A. Person with lower debt to income ratio and current loan status is more likely to pay their loan back then person with higher debt to income ratio and non-current loan.

# 1. Write a lambda function to rearrange positive and negative numbers in a given list
Sample output:
original_list = [-1,2,-3,4,-5,6,-7,8,-9,10,-11,12]
resulting_list = [2,4,6,8,10,12,-11,-9,-7,-5,-3,-1]

In [35]:
original_list = [-1,2,-3,4,-5,6,-7,8,-9,10,-11,12] # our list 

resulting_list =list(filter(lambda x: x >= 0, original_list)) + list(sorted(filter(lambda x: x < 0, original_list)))
# weusing lambda function to make rearrange positive and negative numbers in a given list.

print(resulting_list)

[2, 4, 6, 8, 10, 12, -11, -9, -7, -5, -3, -1]

# 2. Create a new dataframe using week_11/temperatures/temperature.csv file
from last class. It should have the datetime column and one of the cities.
Create a new boolean column called is_freezing that indicates if the
temperature is at or below freezing. Use a lambda to create this column. Is
there a better way to do this than with a lambda?

In [44]:
df = pd.read_csv("temperature.csv",parse_dates=True, index_col='datetime')
new_df = df[['Vancouver']] # get first columns
new_df = new_df.assign(is_freezing = lambda x: x <= 273.15)# add new boolean column using lambda method assign
new_df.dropna(inplace = True)# drop NAN
new_df

                      Vancouver  is_freezing
datetime
2012-10-01 13:00:00  284.630000        False
2012-10-01 14:00:00  284.629041        False
2012-10-01 15:00:00  284.626998        False
2012-10-01 16:00:00  284.624955        False
2012-10-01 17:00:00  284.622911        False
...                         ...          ...
2017-10-27 20:00:00  286.440000        False
2017-10-27 21:00:00  287.870000        False
2017-10-27 22:00:00  288.420000        False
2017-10-27 23:00:00  288.650000        False
2017-10-28 00:00:00  288.010000        False

[44458 rows x 2 columns]

In [45]:
# I think using this code much easier.
new_df = df<=273.15
new_df

,Vancouver,Portland,San Francisco,Seattle,Los Angeles,San Diego,Las Vegas,Phoenix,Albuquerque,Denver,...,Philadelphia,New York,Montreal,Boston,Beersheba,Tel Aviv District,Eilat,Haifa,Nahariyya,Jerusalem
datetime,,,,,,,,,,,,,,,,,,,,,
2012-10-01 12:00:00,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2012-10-01 13:00:00,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2012-10-01 14:00:00,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2012-10-01 15:00:00,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2012-10-01 16:00:00,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2017-11-29 20:00:00,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2017-11-29 21:00:00,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2017-11-29 22:00:00,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2017-11-29 23:00:00,False,False,False,False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,False,False,False
2017-11-30 00:00:00,False,False,False,False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,False,False,False

In [50]:
import numpy as np
df2 = pd.pivot_table(df, index=['Vancouver','Portland','San Francisco','Seattle','Los Angeles','San Diego','Las Vegas','Phoenix','Albuquerque','Denver','Philadelphia','New York','Montreal','Boston','Beersheba','Tel Aviv District','Eilat','Haifa','Nahariyya','Jerusalem'])
df2

                                                                                                                                                                                                                                             Atlanta  \
Vancouver  Portland   San Francisco Seattle    Los Angeles San Diego Las Vegas  Phoenix    Albuquerque Denver     Philadelphia New York   Montreal   Boston     Beersheba  Tel Aviv District Eilat      Haifa      Nahariyya  Jerusalem
245.150000 272.197333 285.947333    271.730667 285.055667  288.8640  286.789000 291.380667 284.680667  285.455667 283.614000   281.780000 278.950000 283.089000 283.984154 286.477937        288.508275 291.524554 286.934173 283.230667  291.922333
248.941201 273.501667 286.601667    272.493333 285.393333  289.2600  288.760000 292.468333 285.468333  285.818333 283.535000   282.166082 279.309860 282.835000 282.256000 288.280000        290.950000 289.906000 280.256000 282.668333  292.376667
250.150000 272.696333 286.421333    274.579667 284.721333  285.8380  282.229667 288.138000 280.513000  283.671333 276.096333   275.530000 263.450000 276.521333 282.249000 290.420000        292.170000 291.824000 283.899000 284.588000  294.588000
254.967248 272.117000 286.829500    272.017000 285.429500  288.4295  286.567000 290.179500 282.629500  282.992000 282.592000   281.756597 278.936152 282.379500 281.840689 288.161349        288.719550 289.888064 280.038013 282.517000  289.179500
258.730320 271.151000 286.026000    270.676000 282.688500  285.3010  282.638500 286.501000 279.113500  281.951000 281.751000   281.483257 277.515947 281.988500 284.724990 289.983457        294.101770 288.588260 286.179827 284.551000  288.563500
...                                                                                                                                                                                                                                              ...
305.900000 310.220000 298.930000    305.190000 305.650000  303.1100  308.150000 312.400000 300.420000  296.100000 303.080000   302.850000 294.590000 300.960000 293.173000 299.350000        301.323000 301.173000 301.173000 299.250000  297.010000
306.060000 308.880000 298.100000    304.370000 302.530000  299.1600  309.820000 310.630000 290.420000  283.650000 296.890000   298.940000 289.770000 295.220000 290.960000 297.850000        298.610000 300.960000 300.960000 297.850000  295.760000
306.690000 309.800000 298.630000    305.420000 304.530000  300.8800  310.370000 312.210000 295.670000  285.280000 298.430000   299.940000 291.140000 296.600000 290.960000 297.650000        298.610000 300.960000 300.960000 297.650000  295.770000
           310.980000 299.390000    305.810000 306.270000  303.1500  310.370000 312.620000 297.840000  291.230000 302.290000   302.730000 293.390000 299.780000 293.173000 298.650000        301.323000 301.173000 301.173000 298.550000  295.890000
307.000000 310.440000 299.340000    306.070000 305.670000  301.9800  310.370000 312.810000 296.790000  286.660000 300.860000   301.700000 292.780000 298.340000 290.960000 298.150000        298.610000 300.960000 300.960000 297.950000  295.630000

                                                                                                                                                                                                                                          Charlotte  \
Vancouver  Portland   San Francisco Seattle    Los Angeles San Diego Las Vegas  Phoenix    Albuquerque Denver     Philadelphia New York   Montreal   Boston     Beersheba  Tel Aviv District Eilat      Haifa      Nahariyya  Jerusalem
245.150000 272.197333 285.947333    271.730667 285.055667  288.8640  286.789000 291.380667 284.680667  285.455667 283.614000   281.780000 278.950000 283.089000 283.984154 286.477937        288.508275 291.524554 286.934173 283.230667   289.4140
248.941201 273.501667 286.601667    272.493333 285.393333  289.2600  288.760000 292.468333 285.468333  285.818333 283.535000   282.166082 279.309860 282.835000 282.256000 288.280000        290.950000 289.906000 280.256000 282.668333   289.8350
250.150000 272.696333 286.421333    274.579667 284.721333  285.8380  282.229667 288.138000 280.513000  283.671333 276.096333   275.530000 263.450000 276.521333 282.249000 290.420000        292.170000 291.824000 283.899000 284.588000   289.9380
254.967248 272.117000 286.829500    272.017000 285.429500  288.4295  286.567000 290.179500 282.629500  282.992000 282.592000   281.756597 278.936152 282.379500 281.840689 288.161349        288.719550 289.888064 280.038013 282.517000   288.0795
258.730320 271.151000 286.026000    270.676000 282.688500  285.3010  282.638500 286.501000 279.113500  281.951000 281.751000   281.483257 277.515947 281.988500 284.724990 289.983457        294.101770 288.588260 286.179827 284.551000   286.7885
...                                                                                                                                                                                                                                             ...
305.900000 310.220000 298.930000    305.190000 305.650000  303.1100  308.150000 312.400000 300.420000  296.100000 303.080000   302.850000 294.590000 300.960000 293.173000 299.350000        301.323000 301.173000 301.173000 299.250000   302.4800
306.060000 308.880000 298.100000    304.370000 302.530000  299.1600  309.820000 310.630000 290.420000  283.650000 296.890000   298.940000 289.770000 295.220000 290.960000 297.850000        298.610000 300.960000 300.960000 297.850000   298.4200
306.690000 309.800000 298.630000    305.420000 304.530000  300.8800  310.370000 312.210000 295.670000  285.280000 298.430000   299.940000 291.140000 296.600000 290.960000 297.650000        298.610000 300.960000 300.960000 297.650000   298.9800
           310.980000 299.390000    305.810000 306.270000  303.1500  310.370000 312.620000 297.840000  291.230000 302.290000   302.730000 293.390000 299.780000 293.173000 298.650000        301.323000 301.173000 301.173000 298.550000   300.6600
307.000000 310.440000 299.340000    306.070000 305.670000  301.9800  310.370000 312.810000 296.790000  286.660000 300.860000   301.700000 292.780000 298.340000 290.960000 298.150000        298.610000 300.960000 300.960000 297.950000   300.1000

                                                                                                                                                                                                                                             Chicago  \
Vancouver  Portland   San Francisco Seattle    Los Angeles San Diego Las Vegas  Phoenix    Albuquerque Denver     Philadelphia New York   Montreal   Boston     Beersheba  Tel Aviv District Eilat      Haifa      Nahariyya  Jerusalem
245.150000 272.197333 285.947333    271.730667 285.055667  288.8640  286.789000 291.380667 284.680667  285.455667 283.614000   281.780000 278.950000 283.089000 283.984154 286.477937        288.508275 291.524554 286.934173 283.230667  277.247333
248.941201 273.501667 286.601667    272.493333 285.393333  289.2600  288.760000 292.468333 285.468333  285.818333 283.535000   282.166082 279.309860 282.835000 282.256000 288.280000        290.950000 289.906000 280.256000 282.668333  276.351667
250.150000 272.696333 286.421333    274.579667 284.721333  285.8380  282.229667 288.138000 280.513000  283.671333 276.096333   275.530000 263.450000 276.521333 282.249000 290.420000        292.170000 291.824000 283.899000 284.588000  273.821333
254.967248 272.117000 286.829500    272.017000 285.429500  288.4295  286.567000 290.179500 282.629500  282.992000 282.592000   281.756597 278.936152 282.379500 281.840689 288.161349        288.719550 289.888064 280.038013 282.517000  276.029500
258.730320 271.151000 286.026000    270.676000 282.688500  285.3010  282.638500 286.501000 279.113500  281.951000 281.751000   281.483257 277.515947 281.988500 284.724990 289.983457        294.101770 288.588260 286.179827 284.551000  277.663500
...                                                                                                                                                                                                                                              ...
305.900000 310.220000 298.930000    305.190000 305.650000  303.1100  308.150000 312.400000 300.420000  296.100000 303.080000   302.850000 294.590000 300.960000 293.173000 299.350000        301.323000 301.173000 301.173000 299.250000  301.910000
306.060000 308.880000 298.100000    304.370000 302.530000  299.1600  309.820000 310.630000 290.420000  283.650000 296.890000   298.940000 289.770000 295.220000 290.960000 297.850000        298.610000 300.960000 300.960000 297.850000  298.640000
306.690000 309.800000 298.630000    305.420000 304.530000  300.8800  310.370000 312.210000 295.670000  285.280000 298.430000   299.940000 291.140000 296.600000 290.960000 297.650000        298.610000 300.960000 300.960000 297.650000  299.680000
           310.980000 299.390000    305.810000 306.270000  303.1500  310.370000 312.620000 297.840000  291.230000 302.290000   302.730000 293.390000 299.780000 293.173000 298.650000        301.323000 301.173000 301.173000 298.550000  301.980000
307.000000 310.440000 299.340000    306.070000 305.670000  301.9800  310.370000 312.810000 296.790000  286.660000 300.860000   301.700000 292.780000 298.340000 290.960000 298.150000        298.610000 300.960000 300.960000 297.950000  300.920000

                                                                                                                                                                                                                                              Dallas  \
Vancouver  Portland   San Francisco Seattle    Los Angeles San Diego Las Vegas  Phoenix    Albuquerque Denver     Philadelphia New York   Montreal   Boston     Beersheba  Tel Aviv District Eilat      Haifa      Nahariyya  Jerusalem
245.150000 272.197333 285.947333    271.730667 285.055667  288.8640  286.789000 291.380667 284.680667  285.455667 283.614000   281.780000 278.950000 283.089000 283.984154 286.477937        288.508275 291.524554 286.934173 283.230667  298.297333
248.941201 273.501667 286.601667    272.493333 285.393333  289.2600  288.760000 292.468333 285.468333  285.818333 283.535000   282.166082 279.309860 282.835000 282.256000 288.280000        290.950000 289.906000 280.256000 282.668333  298.801667
250.150000 272.696333 286.421333    274.579667 284.721333  285.8380  282.229667 288.138000 280.513000  283.671333 276.096333   275.530000 263.450000 276.521333 282.249000 290.420000        292.170000 291.824000 283.899000 284.588000  279.471333
254.967248 272.117000 286.829500    272.017000 285.429500  288.4295  286.567000 290.179500 282.629500  282.992000 282.592000   281.756597 278.936152 282.379500 281.840689 288.161349        288.719550 289.888064 280.038013 282.517000  297.129500
258.730320 271.151000 286.026000    270.676000 282.688500  285.3010  282.638500 286.501000 279.113500  281.951000 281.751000   281.483257 277.515947 281.988500 284.724990 289.983457        294.101770 288.588260 286.179827 284.551000  296.226000
...                                                                                                                                                                                                                                              ...
305.900000 310.220000 298.930000    305.190000 305.650000  303.1100  308.150000 312.400000 300.420000  296.100000 303.080000   302.850000 294.590000 300.960000 293.173000 299.350000        301.323000 301.173000 301.173000 299.250000  295.490000
306.060000 308.880000 298.100000    304.370000 302.530000  299.1600  309.820000 310.630000 290.420000  283.650000 296.890000   298.940000 289.770000 295.220000 290.960000 297.850000        298.610000 300.960000 300.960000 297.850000  294.640000
306.690000 309.800000 298.630000    305.420000 304.530000  300.8800  310.370000 312.210000 295.670000  285.280000 298.430000   299.940000 291.140000 296.600000 290.960000 297.650000        298.610000 300.960000 300.960000 297.650000  294.560000
           310.980000 299.390000    305.810000 306.270000  303.1500  310.370000 312.620000 297.840000  291.230000 302.290000   302.730000 293.390000 299.780000 293.173000 298.650000        301.323000 301.173000 301.173000 298.550000  294.280000
307.000000 310.440000 299.340000    306.070000 305.670000  301.9800  310.370000 312.810000 296.790000  286.660000 300.860000   301.700000 292.780000 298.340000 290.960000 298.150000        298.610000 300.960000 300.960000 297.950000  294.330000

                                                                                                                                                                                                                                             Detroit  \
Vancouver  Portland   San Francisco Seattle    Los Angeles San Diego Las Vegas  Phoenix    Albuquerque Denver     Philadelphia New York   Montreal   Boston     Beersheba  Tel Aviv District Eilat      Haifa      Nahariyya  Jerusalem
245.150000 272.197333 285.947333    271.730667 285.055667  288.8640  286.789000 291.380667 284.680667  285.455667 283.614000   281.780000 278.950000 283.089000 283.984154 286.477937        288.508275 291.524554 286.934173 283.230667  287.239000
248.941201 273.501667 286.601667    272.493333 285.393333  289.2600  288.760000 292.468333 285.468333  285.818333 283.535000   282.166082 279.309860 282.835000 282.256000 288.280000        290.950000 289.906000 280.256000 282.668333  287.285000
250.150000 272.696333 286.421333    274.579667 284.721333  285.8380  282.229667 288.138000 280.513000  283.671333 276.096333   275.530000 263.450000 276.521333 282.249000 290.420000        292.170000 291.824000 283.899000 284.588000  274.704667
254.967248 272.117000 286.829500    272.017000 285.429500  288.4295  286.567000 290.179500 282.629500  282.992000 282.592000   281.756597 278.936152 282.379500 281.840689 288.161349        288.719550 289.888064 280.038013 282.517000  286.329500
258.730320 271.151000 286.026000    270.676000 282.688500  285.3010  282.638500 286.501000 279.113500  281.951000 281.751000   281.483257 277.515947 281.988500 284.724990 289.983457        294.101770 288.588260 286.179827 284.551000  286.101000
...                                                                                                                                                                                                                                              ...
305.900000 310.220000 298.930000    305.190000 305.650000  303.1100  308.150000 312.400000 300.420000  296.100000 303.080000   302.850000 294.590000 300.960000 293.173000 299.350000        301.323000 301.173000 301.173000 299.250000  301.800000
306.060000 308.880000 298.100000    304.370000 302.530000  299.1600  309.820000 310.630000 290.420000  283.650000 296.890000   298.940000 289.770000 295.220000 290.960000 297.850000        298.610000 300.960000 300.960000 297.850000  297.400000
306.690000 309.800000 298.630000    305.420000 304.530000  300.8800  310.370000 312.210000 295.670000  285.280000 298.430000   299.940000 291.140000 296.600000 290.960000 297.650000        298.610000 300.960000 300.960000 297.650000  298.730000
           310.980000 299.390000    305.810000 306.270000  303.1500  310.370000 312.620000 297.840000  291.230000 302.290000   302.730000 293.390000 299.780000 293.173000 298.650000        301.323000 301.173000 301.173000 298.550000  300.870000
307.000000 310.440000 299.340000    306.070000 305.670000  301.9800  310.370000 312.810000 296.790000  286.660000 300.860000   301.700000 292.780000 298.340000 290.960000 298.150000        298.610000 300.960000 300.960000 297.950000  300.490000

                                                                                                                                                                                                                                             Houston  \
Vancouver  Portland   San Francisco Seattle    Los Angeles San Diego Las Vegas  Phoenix    Albuquerque Denver     Philadelphia New York   Montreal   Boston     Beersheba  Tel Aviv District Eilat      Haifa      Nahariyya  Jerusalem
245.150000 272.197333 285.947333    271.730667 285.055667  288.8640  286.789000 291.380667 284.680667  285.455667 283.614000   281.780000 278.950000 283.089000 283.984154 286.477937        288.508275 291.524554 286.934173 283.230667  297.630667
248.941201 273.501667 286.601667    272.493333 285.393333  289.2600  288.760000 292.468333 285.468333  285.818333 283.535000   282.166082 279.309860 282.835000 282.256000 288.280000        290.950000 289.906000 280.256000 282.668333  297.293333
250.150000 272.696333 286.421333    274.579667 284.721333  285.8380  282.229667 288.138000 280.513000  283.671333 276.096333   275.530000 263.450000 276.521333 282.249000 290.420000        292.170000 291.824000 283.899000 284.588000  285.138000
254.967248 272.117000 286.829500    272.017000 285.429500  288.4295  286.567000 290.179500 282.629500  282.992000 282.592000   281.756597 278.936152 282.379500 281.840689 288.161349        288.719550 289.888064 280.038013 282.517000  297.117000
258.730320 271.151000 286.026000    270.676000 282.688500  285.3010  282.638500 286.501000 279.113500  281.951000 281.751000   281.483257 277.515947 281.988500 284.724990 289.983457        294.101770 288.588260 286.179827 284.551000  295.338500
...                                                                                                                                                                                                                                              ...
305.900000 310.220000 298.930000    305.190000 305.650000  303.1100  308.150000 312.400000 300.420000  296.100000 303.080000   302.850000 294.590000 300.960000 293.173000 299.350000        301.323000 301.173000 301.173000 299.250000  300.680000
306.060000 308.880000 298.100000    304.370000 302.530000  299.1600  309.820000 310.630000 290.420000  283.650000 296.890000   298.940000 289.770000 295.220000 290.960000 297.850000        298.610000 300.960000 300.960000 297.850000  300.630000
306.690000 309.800000 298.630000    305.420000 304.530000  300.8800  310.370000 312.210000 295.670000  285.280000 298.430000   299.940000 291.140000 296.600000 290.960000 297.650000        298.610000 300.960000 300.960000 297.650000  301.440000
           310.980000 299.390000    305.810000 306.270000  303.1500  310.370000 312.620000 297.840000  291.230000 302.290000   302.730000 293.390000 299.780000 293.173000 298.650000        301.323000 301.173000 301.173000 298.550000  301.510000
307.000000 310.440000 299.340000    306.070000 305.670000  301.9800  310.370000 312.810000 296.790000  286.660000 300.860000   301.700000 292.780000 298.340000 290.960000 298.150000        298.610000 300.960000 300.960000 297.950000  301.780000

                                                                                                                                                                                                                                          Indianapolis  \
Vancouver  Portland   San Francisco Seattle    Los Angeles San Diego Las Vegas  Phoenix    Albuquerque Denver     Philadelphia New York   Montreal   Boston     Beersheba  Tel Aviv District Eilat      Haifa      Nahariyya  Jerusalem
245.150000 272.197333 285.947333    271.730667 285.055667  288.8640  286.789000 291.380667 284.680667  285.455667 283.614000   281.780000 278.950000 283.089000 283.984154 286.477937        288.508275 291.524554 286.934173 283.230667    290.964000

# 3. BONUS: if you still have time, try to do a pivot of the data in question 2 so you have the hourly data for all the cities and a flag for if it's freezing

In [39]:
table = pd.pivot(data = df,index = ['True'])
table

TypeError: pivot() missing 1 required argument: 'columns'